ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  #- id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

# - repo: https://github.com/crate-ci/typos
#   rev: v1.29.4
#   hooks:
#   - id: typos

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.1
  hooks:
  - id: uv-lock

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']


- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo-fmt
    language: system
    files: \.rs$
    entry: cargo fmt -- --check
  # - id: cargo-clippy
  #   name: cargo-clippy
  #   language: system
  #   files: \.rs$
  #   entry: cargo clippy --all-targets --all -- -D warnings   # Use -D warnings option to ensure the job fails when encountering warnings
  #   pass_filenames: false
