[project]
name = "rlic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Clément Robert", email = "cr52@protonmail.com" }
]
requires-python = ">=3.9"
dependencies = ["numpy>=2.0.0"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
test = [
    "pytest>=8.1.0",
]

[tool.maturin]
module-name = "rlic._core"
python-packages = ["rlic"]
python-source = "src"

[tool.pytest.ini_options]
filterwarnings = [
  "error",
]
xfail_strict = true
