[project]
name = "lick-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Clément Robert", email = "cr52@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = ["numpy>=2.0.0"]

[tool.maturin]
module-name = "lick_core._core"
python-packages = ["lick_core"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
